services:
  frontend:
    build: .
    ports:
      - "8081:5173" # localhost:8081 expone el puerto 5173 interno
    volumes: #comentar desde aqui
      - .:/app 
    working_dir: /app
    command: npm run dev -- --host #hasta aqui para que no haya dev-tools
    networks:
      - pomse_back_laravel # misma red que tu API
    restart: always

networks:
  pomse_back_laravel:
    external: true 